We have next logging message:2024-11-16 17:22:19,380:ERROR - division by zero
Traceback (most recent call last):
  File "D:\repos\logs-and-test\main.py", line 10, in <module>
    print(10/0)
          ~~^~
ZeroDivisionError: division by zero
We have next logging message:2024-11-16 17:24:54,403:ERROR - name 'a' is not defined
Traceback (most recent call last):
  File "D:\repos\logs-and-test\main.py", line 10, in <module>
    print(a)
          ^
NameError: name 'a' is not defined
We have next logging message:2024-11-16 17:25:17,658:ERROR - name 'lgjkkshgk' is not defined
Traceback (most recent call last):
  File "D:\repos\logs-and-test\main.py", line 10, in <module>
    print(lgjkkshgk)
          ^^^^^^^^^
NameError: name 'lgjkkshgk' is not defined
